version: "3.8"

services:
  db:
    image: postgres:16
    container_name: todo_list_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  db_test:
#    image: postgres:16
#    container_name: todo_list_postgres_test
#    environment:
#      POSTGRES_USER: ${DB_TEST_USER}
#      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
#      POSTGRES_DB: ${DB_TEST_NAME}
#    ports:
#      - "${DB_TEST_HOST_PORT}:${DB_TEST_PORT}"
#    volumes:
#      - postgres_test_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo_list_app
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  postgres_data:
#  postgres_test_data:
